package com.globalcarelink.agents.documentation.models;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * API 문서화 모델
 */
@Data
@Builder
public class ApiDocumentation {
    private String documentationId;
    private String title;
    private String description;
    private String version;
    private String format; // "OPENAPI", "MARKDOWN", "HTML"
    
    // 문서 내용
    private String content;
    private Map<String, Object> structuredContent; // OpenAPI 스펙 등
    
    // 문서 품질
    private DocumentationQuality quality;
    
    // 생성 정보
    private LocalDateTime generatedAt;
    private LocalDateTime lastUpdated;
    private String generatedBy;
    private boolean autoGenerated;
    
    // 메타데이터
    private Map<String, String> metadata;
    private String filePath;
    private long fileSize;
}

@Data
@Builder
class DocumentationQuality {
    private String overallGrade; // A+, A, B+, B, C+, C, D, F
    private double completeness; // 0.0 - 1.0
    private double accuracy; // 0.0 - 1.0
    private double readability; // 0.0 - 1.0
    private int missingFields;
    private int errorCount;
}