# 자동 리뷰어 할당 설정
addReviewers: true
addAssignees: true

# 리뷰어 목록
reviewers:
  - dooseob
  # 팀원 추가 시 여기에 GitHub 사용자명 추가

# PR 작성자를 assignee로 추가
addAssignees: author

# 리뷰어 수
numberOfReviewers: 1

# PR 작성자를 리뷰어 목록에서 제외
skipKeywords:
  - wip
  - draft

# 팀별 리뷰어 그룹 (향후 팀 확장 시 사용)
# reviewerGroups:
#   backend:
#     - backend-dev1
#     - backend-dev2
#   frontend:
#     - frontend-dev1
#     - frontend-dev2