version: 2
updates:
  # Java/Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "dooseob"
    assignees:
      - "dooseob"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      spring:
        patterns:
          - "org.springframework*"
      testing:
        patterns:
          - "*test*"
          - "*junit*"
          - "*mockito*"

  # Node.js/npm dependencies  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "dooseob"
    assignees:
      - "dooseob"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # 메이저 버전 업데이트는 수동으로 처리
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      testing:
        patterns:
          - "*test*"
          - "*jest*"
          - "*vitest*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "dooseob"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "dooseob"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"