version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: elderberry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass elderberry123!
    restart: unless-stopped
    networks:
      - elderberry-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: elderberry-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:elderberry123!
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - elderberry-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  elderberry-network:
    driver: bridge