spring:
  datasource:
    url: jdbc:sqlite::memory:
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  logging:
    level:
      org.hibernate.SQL: WARN
      com.globalcarelink: INFO