# 814줄 Claude 지침 진화 시스템 데모 설정
spring:
  profiles:
    active: demo
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:evolution_demo
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 로깅 설정
logging:
  level:
    com.globalcarelink.agents.evolution: INFO
    com.globalcarelink.agents: DEBUG
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 진화 시스템 설정
evolution:
  system:
    enable-auto-evolution: true
    statistical-significance-threshold: 5
    improvement-threshold: 0.15
    max-evolved-versions: 10
    ab-test-duration-days: 7