spring:
  datasource:
    # H2 파일 모드 사용 - 테스트 간 데이터 유지 및 디버깅 용이
    url: jdbc:h2:file:./test-data/testdb;AUTO_SERVER=TRUE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    # HikariCP 최적화 설정
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 시작 시 스키마 재생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false # 성능 테스트 시 로그 최소화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: false
        # 배치 처리 최적화
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        # 2차 캐시 비활성화 (테스트 환경)
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # H2 콘솔 활성화 (테스트 디버깅용)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # 테스트 전용 캐시 설정
  cache:
    type: simple # 단순 메모리 캐시 사용
  
  logging:
    level:
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
      com.globalcarelink: INFO
      # 테스트 실행 과정 로깅
      org.springframework.test: INFO
      org.springframework.transaction: WARN

# 테스트 전용 설정
test:
  # 성능 테스트 임계값 설정
  performance:
    max-query-time-ms: 100
    max-batch-size: 1000
  
  # 테스트 데이터 설정
  data:
    enable-test-data-loading: true
    reset-between-tests: true

# Awaitility 설정 (비동기 테스트용)
awaitility:
  default-timeout: 10s
  default-poll-delay: 100ms